version: '2.4'
services:
  db:
    image: mysql
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: app
      MYSQL_PASSWORD: exemplo
    volumes:
      - /var/lib/mysql
    restart: always
    ports: 
      - 3306:3306
    restart: on-failure
  naming-server:
    build:
      context: naming-server
    ports:
      - 8671:8671
      - 8888:8888
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8671"]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: on-failure
  user-service:
    build:
      context: user-service
    ports:
      - 8090:8090
    restart: on-failure
    depends_on: 
      naming-server:
        condition: service_healthy
  music-service:
    build:
      context: music-service
    ports:
      - 8100:8100
    restart: on-failure
    depends_on: 
      naming-server:
        condition: service_healthy
  artist-service:
    build:
      context: artist-service
    ports:
      - 8200:8200
    restart: on-failure
    depends_on: 
      naming-server:
        condition: service_healthy
  playlist-service:
    build:
      context: playlist-service
    ports:
      - 8500:8500
    restart: on-failure
    depends_on: 
      naming-server:
        condition: service_healthy
  payment-api-service:
    build:
      context: payment-api-service
    ports:
      - 8600:8600
    restart: on-failure
    depends_on: 
      naming-server:
        condition: service_healthy
