server:
  port: 8500
spring:
  application:
    name: playlist-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aps-playlist-service
    username: wildclown
    password: G@briel123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    url: jdbc:mysql://localhost:3306/aps-artist-service
    schemas: aps-artist-service
    user: wildclown
    password: G@briel123
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka

