server:
  port: 8500
spring:
  application:
    name: playlist-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db/database
    username: app
    password: exemplo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    url: jdbc:mysql://db:3306/database
    schemas: aps-user-service
    user: app
    password: examplo
eureka:
  client:
    service-url:
      defaultZone: http://naming-server:8671/eureka

